executable = sub_toys.sh
arguments = $(ProcId)
output                = /home/chenghan/CMSSW_10_2_13/src/flashggFinalFit/Plots/SplusBModels/toys/jobs/sub_toys.$(ClusterId).$(ProcId).out
error                 = /home/chenghan/CMSSW_10_2_13/src/flashggFinalFit/Plots/SplusBModels/toys/jobs/sub_toys.$(ClusterId).$(ProcId).err
log                   = /home/chenghan/CMSSW_10_2_13/src/flashggFinalFit/Plots/SplusBModels/toys/jobs/sub_toys.$(ClusterId).log

on_exit_hold = (ExitBySignal == True) || (ExitCode != 0)
periodic_release =  (NumJobStarts < 3) && ((CurrentTime - EnteredCurrentStatus) > 600)

+JobFlavour = "workday"
queue 500
